### ISSUE TITLE
Device Transmit Load

### ISSUE THREAD

**Issue by laefolson** [koktail-nl/com.leviton.issues#4]
**Describe the bug**
I'm using the new Homey Pro 2023 and having difficulty adding Leviton z-wave switches and dimmers. I'm able to add approximately 10 before I begin to get failures - typically after the device has been recognized and the app is trying to register and install the device in the network. Failures are typically an error message saying that the app lost communication with the device. In some cases I get 'unknown device's in the z-wave registry in the Homey Developer Tools view. Those devices can typically be communicated with on a test, but do not show up in the app.  All the devices are mains powered dimmers, and I've also added one switch. There is also one Leviton dimmer that refuses to be recognized as a Leviton dimmer, and was added in as a generic z-wave device. The dimming function doesn't work on that device, but it does turn on and off.

Behaviorally, as I added in devices the first time and had a number of 'unknown devices' in the z-wave registry, I noticed that the Homey App was "waiting for the z-wave network" for a longer and longer time as an initial message before allowing me to progress with the add steps. Once that started happening for several seconds I started having issues with the device adds.

I've noticed that my Leviton dimmer that was added as a generic z-wave device (Great Room Rail Lights) has very small number of z-wave Tx and Rx, only incrementing when the device is used to turn on and off. The rest of the Leviton added dimmers and switches have high levels of Tx and Rx, along with errors. These are all in the same room within 25 feet of the Homey Pro hub. I've added a screen shot of the Nodes from the Homey Developer Tools which shows the activity for about 24 hours.

**To Reproduce**
I ran into this issue as I was migrating from a prior hub, so know that all of these devices worked fine in the old z-wave network. I've been excluding and resetting them prior to adding them into the new Homey Pro network. When I ran into the issue of getting regular device addition failures, I reset the entire z-wave network from the developer tools and started over. Again, was able to add devices without issue until I got to about 9-10, and then started getting failures.

**Expected behavior**
Given that I have a number of these switches in close proximity to the hub or no more than 1 hop away, I would expect these switches to add in without difficulty.

**Screenshots**
![image](https://github.com/koktail-nl/com.leviton.issues/assets/23406423/9dcf7047-3e65-4140-bf33-9ddfcb17658c)

**Desktop (please complete the following information):**
 - OS: Mac OS 13.4.1
 - Browser Chrome
 - Version 114.0.5735.198 

**Smartphone (please complete the following information):**
 - Device: iPhone 12 Mini
 - OS: 16.5.1
 - Browser Chrome
 - Version 114.0.5735.124

**Additional context**
I'm pretty familiar with technology in general, and this certainly feels like the z-wave network is becoming busy with transmits that might be unnecessary. Devices that started failing on my first attempt added right in once I reset the network and started with different dimmers.

**Comment by koktaildotcom** [comment]
Could be related to: https://github.com/koktail-nl/com.leviton.issues/issues/3

**Comment by koktaildotcom** [comment]
The devices does not support direct reporting from the devices and we need to have a polling mechanism to get the status unfortunately. I have changed to default polling interval to 10 seconds (in favor of 3) and created a new release. Can you please test if this solves your issue.

The build can be installed here: https://homey.app/en-us/app/com.leviton/Leviton/test/
